title: Turner Luke
logo: "/images/myFaceCirc.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <p align="center">
    <a href="https://www.linkedin.com/in/turnermluke/">LinkedIn</a>
    •
    <a href=https://github.com/turnerluke/turnerluke/blob/main/Turner%20Luke%20Resume.pdf>Resume</a>
    •
    <a href=https://github.com/turnerluke/TurnerLuke.github.io>Portfolio</a>
    •
    <a href=https://medium.com/@turnermluke>Medium Blogposts</a>
  </p>
  
  <br>
  
  Medical device engineer seeking to translate passion for quantitative analysis into a data science career.
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
