title: 
 <p align="center">
   Turner Luke
 </p>
 
logo: "/images/myFaceCirc.png?raw=true"  # Bio image

description: > # Bio text (Left side)
 
  <p align="center">
    <a href="https://www.linkedin.com/in/turnermluke/">LinkedIn</a>
    |
    <a href=https://github.com/turnerluke/turnerluke/blob/main/Turner%20Luke%20Resume.pdf>Resume</a>
    |
    <a href=https://medium.com/@turnermluke>Medium</a>
  </p>
  
  <br>
  
  Medical device engineer seeking to translate passion for quantitative analysis into a data science career.
  <br><br>
  Graduated from The University of Wisconsin - Madison with a B.S. Chemical Engineering, chemistry double major.
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
